- README.md
- bench_test.go
- gobrake.go
- notice.go
- notifier.go
```
benchmark                 old ns/op     new ns/op     delta
BenchmarkSendNotice-4     32225         31622         -1.87%
benchmark                 old allocs     new allocs     delta
BenchmarkSendNotice-4     122            120            -1.64%
benchmark                 old bytes     new bytes     delta
BenchmarkSendNotice-4     8586          7739          -9.86%
```
> Add new API and speedup notice sending.

- .travis.yml
- notice.go
- notifier_test.go
- util.go
TODO:
Errors created by pkg/errors capture the stacktrace of the place when
the errors are created. It makes debugging much more easier if
developers can see the real origin of the errors.
This commit introduces the special handling of errors from the
pkg/errors package.
Fixes #37 
Signed-off-by: Tibor Benke <ihrwein@gmail.com>
> Extract stacktraces from errors of the pkg/errors package

- stack.go
The breaking upstream change https://github.com/pkg/errors/commit/4f47277723cbe176eaef3bccb66a69de7a531157 caused builds to fail.
Patch to fix the type error and restore working builds.
> Fix build error introduced by pkg/errors dependency

- stack.go
This reverts commit ebf2122579246386e87e21e68f3d4366edb8399b.
Closes https://github.com/airbrake/gobrake/pull/90
> Revert "Fix build error introduced by pkg/errors dependency"

- README.md
It's easy to guess how to install gobrake with some basic `go get`
knowledge, but it's nicer to provide our gophers a one liner to quickly
copy and paste.
> Add a section for installing gobrake

- .travis.yml
go1.13 was released on 2019/09/03:
https://golang.org/doc/devel/release.html#go1.13
> travis: test against go1.13

- notifier_test.go
Running the test suite locally yields 3 failures.
This is probably because some of the tests were catered for one machine (or CI),
so that they can pass only there. However on my computer gobrake collects
slightly different information.
Therefore, by making our expectations a bit more loose, we can make the tests
pass everywhere.
> notifier_test: fix failing tests

- metric_test.go
Fixes #126 (Sporadic test failure in metric_test.go)
This seems to be the least painful solution, which requires almost no effort.
> metric_test: broaden allowed threshold to 20ms

- gobrake.go
- notifier.go
- notifier_test.go
Replaces #119 (Log SendNotice errors)
As of now gobrake's Notify call happily exits without telling anything no matter
if the error was sent or not. The user has no idea about the status. It can also
choke silently if you specify your project credentials incorrectly. This is not
very welcoming and it's also a potential debugging time sink (been there, done
that).
In order to be more vocal, we start logging these errors, so that now you can
have an idea why your notice is not delivered. On success we don't print
anything (same behaviour as before).
> notifier: log configuration errors and such

- notifier_test.go
Fixes #134 (Use fixtures for code hunk testing)
It turned out that we don't need fixtures to test that code. The expectations
can be simplified, so we just check that backtrace is not zero.
We already have fixtures that do what I had intended to
do (internal/testpkg1). We already cover code hunks in our tests.
> notifier_test: stop checking backtrace content

- README.md
- example_test.go
- filter.go
- notifier.go
- notifier_test.go
Deprecate "KeysBlacklist" in favor of "KeysBlocklist"
https://github.com/airbrake/gobrake#keysblacklist
Clone this example Go repo I made for this purpose:
https://github.com/thompiler/go-example
```
git clone git@github.com:thompiler/go-example.git
```
Install this version of the notifier:
```
go get github.com/airbrake/gobrake/v4@update-filtering-term
```
Replace placeholders with project credentials:
https://github.com/thompiler/go-example/blob/master/main.go#L12-L13
```go
var airbrake = gobrake.NewNotifierWithOptions(&gobrake.NotifierOptions{
ProjectId:     123,            // Replace with project ID
ProjectKey:    "abcdef123456", // Replace with project API key
KeysBlocklist: blocklist,      // Change to "KeysBlocklist" to test deprecated option
})
```
Run the project:
```
go run …
```
> Update filtering terminology

- README.md
- There was a mix of tabs and spaces; changed everything to tabs
- Changed format of markdown's headings for consistency
- Replaced all the hardcoded ProjectId with `<YOUR PROJECT ID>`
- Replaced all the hardcoded ProjectKey with `<YOUR API KEY>`
- Added Environment to default examples
- Added section headers
- Sorted options by importance
- Added Negroni example
> README.md: update and copy tweaks

- CHANGELOG.md
- notifier.go
- notifier_test.go
This new option will likely not be used by our customers directly through the
gobrake config. However we need this option to support remote configuration, so
that its value will be decided/changed at runtime.
The option basically turns on/off `airbrake.Notify()` calls.
> notifier: add the DisableErrorNotifications option

- CHANGELOG.md
- notifier.go
- notifier_test.go
- queries.go
- queues.go
- route_breakdown.go
- routes.go
This new option will likely not be used by our customers directly through the
gobrake config. However we need this option to support remote configuration, so
that its value will be decided/changed at runtime.
The option basically turns on/off these calls:
* airbrake.Queues.Notify
* airbrake.Routes.Notify
* airbrake.Queries.Notify
> Add the DisableAPM option

- README.md
While these examples are still not copy-paste friendly (since they assume they
are integrated into a bigger codebase), we can fix some mistakes with regard to
non-existent keys and missing arguments, which we pass to some functions.
> README: fix mistakes in APM documentation

- CHANGELOG.md
- notifier.go
- queries.go
- queues.go
- route_breakdown.go
- routes.go
This option is similar to the `Host` option but it allows configuring host to
which APM data should be sent to.
Configuring this manually probably doesn't make much sense but it will be used
in the upcoming remote configuration work.
> Add the 'APMHost' option

- notifier.go
- queries.go
- queues.go
- route_breakdown.go
- routes.go
This is going to be used mostly by the remote configuration features. At the
moment you can configure `Host` and `APMHost` options to route your traffic,
however these values are static (cannot be changed at runtime).
With this commit we can redefine these two options and runtime and the traffic
will be redirected to the new location.
> Add ability to change reroute traffic at runtime

- bench_test.go
- notifier.go
- notifier_test.go
- race_test.go
- remote_config.go
- remote_config_test.go
Gobrake needs to be able to fetch remote configuration at certain
intervals. This commit prepares gobrake for the change. A newly created notifier
will start polling S3 for the config immediately. The config values are not used
at the moment, we just make reads and discard the config to keep the change as
simple as possible.
> Fetch remote configuration every 10 minutes

- metric_test.go
- notifier_test.go
Fixes #152 (Make it possible to run tests without an internet connection)
Now they're faster and can run without an active internet connection. Yay!
> Fix specs that require an internet connection

- beego/filter.go
- notifier.go
- notifier_test.go
- remote_config.go
The old way wasn't copying the struct properly. When we modified the copy, the
original struct was also modified. The new way of copying is manual but it
works!
> remote_config: copy notifier opts properly

- CHANGELOG.md
- metric.go
- metric_test.go
Fixes #155 (Bug: `gobrake: span="http.client" is already finished`)
> metric: fix unwanted "span="http.client" is already finished"

- CHANGELOG.md
- remote_config.go
- remote_config_test.go
Fixes #176 (Gobrake v5 is not respecting the HTTPClient)
> remote_config: use user-provided HTTPClient, not the default one

- CHANGELOG.md
- remote_config.go
Fixes #177 (Remote configuration: write config.json to a writeable place)
This can happen if, for example, gobrake is running inside a Docker container.
> remote_config: fallback config loading/dumping to /tmp

- CHANGELOG.md
- remote_config.go
- remote_config_test.go
Our current message provides a reason why the config is not fetched but it
doesn't give any clue what URL is being requested. By printing the requested URL
it's easier to debug certain scenarios.
> remote_config: improve error message when config is not fetched

- .gitignore
- CHANGELOG.md
- notifier_test.go
- race_test.go
- remote_config.go
- remote_config_test.go
Fixes #185 (dumpConfig failed: no such file or directory)
Some of our users complain that gobrake tries to dump the remote config that we
pull from S3 to the GOPATH directory. The OS user that is running the code may
not have write access to that directory and therefore writing the remote config
will fail. This is especially evident when gobrake runs inside a
container. Persistency in a container makes no sense.
There's no good universal location to keep persistent remote config, so it's
easier just to delete the config.
> remote_config: delete the code for config dumping/loading

- CHANGELOG.md
- README.md
- notifier.go
- notifier_test.go
This new option configures the remote configuration feature.
Note: it is not recommended to disable this feature. It might negatively impact
how your notifier works. Please use this option with caution.
> notifier: add the DisableRemoteConfig option

- beego/filter.go
When the `response status` is ok, the beego application sets it to `0`. To fix that when we send the notice to airbrake, we overwrite the status to StatusOK i.e. `200`
> Beego Status fix

- README.md
- examples/apexlog/main.go
- examples/zerolog/main.go
- go.mod
- go.sum
- zerolog/zerolog.go
Add in zerolog support for Gobrake
Cuz zerolog is super rad yo
> add in zerolog integration

- zerolog/zerolog.go
* update zerolog integration to check for a couple special fields, and if present, move them from `Notice.Params` to `Notice.Context`
* deferring to @chimanjain to assert correctness and complete
@chimanjain I learned recently that if you put `route`, and `httpMethod` keys on the `Notice.Context` then the Airbrake dashboard will automatically link reported errors to the route/method combination in one of the performance dashboards. Basically, we realized that as part of our integrations, we have been sending the `route` and `httpMethod` keys on the `Notice.Params` by mistake. By moving these two key/values over to the `Notice.Context` we get the added benefit described above.
> Update Zerolog integration for automatic linking of errors to routes

- apexlog/apexlog.go
Update apex/log handler to check for a couple special fields i.e. `route` and `httpMethod`, and if present, move them from `Notice.Params` to `Notice.Context` for automatic linking of errors to routes.
> Update apex/log handler for automatic linking of errors to routes

- gin/middleware.go
- negroni/middleware.go
* Deprecate Negroni NewMiddleware() function.
* Deprecate Gin NewMiddleware() function in favour of New() function.
> Deprecate middleware functions

- backlog.go
- notifier.go
- queries.go
- queues.go
- route_breakdown.go
- route_stat.go
The Backlog class accepts notices and APM events and synchronously sends them in
the background at regular intervals (1 minute).
The notices that it accepts are those that have failed to be sent due to network
issues or Airbrake servers struggling. If the second attempt fails, then such
data is discarded forever.
The maximum backlog size is 100.
> Add Backlog Functionality

- notifier.go
- notifier_test.go
- queries.go
- queues.go
- route_breakdown.go
- route_stat.go
For the time being, if a response receives a 429 error, it will check to see if X-RateLimit-Delay is present or not in headers. If it is not, it will send the message 'X-RateLimit-Delay header is missing', otherwise it will compute the rate limit and send the static message 'IP is rate limited'.
Need to change
--------------
Replace the static message that says 'IP is rate limited' with the message that is received from the response body.
> Show proper error message which API gives 429 response

- .github/workflows/test.yml
Latest GolangCI Lint doesn't support go1.17 anymore but we still do. Locking to
an older GolangCI Lint doesn't work properly, so it's easier to stop testing
against go1.17.
> .github/workflows/test: stop testing against go1.17
