airbrake/gobrake

- README.md
- circle.yml
- notifier.go
- notifier_test.go
Fixes https://github.com/airbrake/gobrake/issues/22#issuecomment-240699641
> Don't panic if notifier is closed twice.

- code_hunk.go
- lrucache/lrucache.go
- notice.go
Fixes https://github.com/airbrake/gobrake/issues/42
> Don't log error when source file does not exist

- notice.go
> Add Notice.SetRequest method

- notifier.go
- notifier_test.go
> Handle 413 response status code from Airbrake server.

- example_test.go
- notifier.go
- notifier_test.go
> Add NewBlacklistKeysFilter.

- filter.go
- notifier.go
Fixes https://github.com/airbrake/gobrake/issues/62
> Use SOURCE_VERSION on Heroku

- git.go
- internal_test.go
> Add findGitDir function

- filter.go
- git.go
> Use findGitDir to find git directory.

- notifier.go
Replaces https://github.com/airbrake/gobrake/pull/78
> Fix SendNoticeAsync to send queued notices when notifier is closed

- notice.go
- stack.go
Fixes https://github.com/airbrake/gobrake/issues/85
> Use runtime.CallersFrames

- README.md
- beego/filter.go
- bench_test.go
- gin/middleware.go
- notifier.go
- notifier_test.go
- routes.go
> Add route notifier filter.

- filter.go
- notifier.go
- notifier_test.go
> Filter errors message by prefix.

- README.md
These instructions needed a bit of a refresh as the API changed. It's
helpful to provide an example in the context of performance monitoring
with the net/http package.
> Add net/http middleware performance example

- README.md
Migrating the Guides to official docs.
> Migrate readme to official docs

- examples/http/README.md
- examples/http/main.go
- http/httpbrake.go
Added gobrake-net/http middleware
Added sample application
> gobrake-http middleware and example application

- examples/gorilla/main.go
- go.mod
- go.sum
- gorilla/gorillabrake.go
Added gobrake-gorilla/mux middleware
Added sample application
> gobrake-gorilla middleware and example application

- examples/fasthttp/README.md
- examples/fasthttp/main.go
- fasthttp/fasthttpbrake.go
- go.mod
Added gobrake-fasthttp middleware
Added sample application
> gobrake-fasthttp middleware and example application

- .github/workflows/test.yml
- go.mod
* Updated go version to 1.17 in go.mod file
* Updated test workflow to support `go 1.19` and remove `1.16`
> Updated go version to 1.17

- notifier.go
- queries.go
- queues.go
- route.go
- route_breakdown.go
- route_stat.go
* Reorganized codebase
* Group constant declaration
* Better error handling for APM
> Refactoring code

- echo/echobrake.go
This PR fixes the metric start and end times, otherwise it shows info as in the screenshot bellow:
> fix metric start

- CHANGELOG.md
- backlog.go
Fixes https://github.com/airbrake/gobrake/issues/350
(segmentation fault when sending notice)
> backlog: continue when there's an error to avoid segfaults

- CHANGELOG.md
- notifier.go
This will release version 5.6.2, after merging we can git tag and push the latest on the main branch.
> Updates for v5.6.2 release
